// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrUVS-ceYK0hz8as7oIvhZGECLvmnsN-M',
    appId: '1:183502417816:web:fdc4f2fe663b87ac6a05ed',
    messagingSenderId: '183502417816',
    projectId: 'rate-my-apartment',
    authDomain: 'rate-my-apartment.firebaseapp.com',
    storageBucket: 'rate-my-apartment.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQdB2qPlDvzt5MsfZ9G3SjBmIL0OmPGd0',
    appId: '1:183502417816:android:a81a7de8f62a00926a05ed',
    messagingSenderId: '183502417816',
    projectId: 'rate-my-apartment',
    storageBucket: 'rate-my-apartment.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5W-X3rsJFUoeE7jN2qX-RzMddPtHFj2M',
    appId: '1:183502417816:ios:041c28cb88f3bc7a6a05ed',
    messagingSenderId: '183502417816',
    projectId: 'rate-my-apartment',
    storageBucket: 'rate-my-apartment.appspot.com',
    iosClientId: '183502417816-27a67eslh4vc4qndpo6agp10itbadj1b.apps.googleusercontent.com',
    iosBundleId: 'com.purdueflutter.RatePurdueApartment',
  );
}
